### ISSUE TITLE
New feature: UI improvement

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447_product_front_porch_webpage#8]
# My Problem

Make the UI nicer, and make the drag and drop UI better looking to match the Boostrap style, maybe like so.

![Screen Shot 2019-12-11 at 9 09 54 AM](https://user-images.githubusercontent.com/411114/70603021-02bbfa80-1bf6-11ea-8ea2-90ffc86476e7.png)

# Solution

![PDF document](https://user-images.githubusercontent.com/411114/70602158-0cdcf980-1bf4-11ea-878d-5a93cfbdbbc0.jpg)

**Comment by rheckart** [comment]
I just pushed a change to master that implements most of these features. I looks like the vertical spacing between Time left, Upload button, the hr and copyright at the bottom are all already 1rem apart from each other. Do you want the margins to be something different?

**Comment by davidgatti** [comment]
Regarding the margin, they might have 1rem set, but it seams the <p> has an additional margin that ads to the 1 that is already there, so it be nice to normalize this so the margins are visually identical, and not technical identical.

**Comment by davidgatti** [comment]
<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/411114/70847900-2e471b00-1e6a-11ea-970c-226a7e6fd894.png">

@rheckart change of plans (the margin issue still valid). After looking at the latest changes I decided to change how we make the UI, since we can't drift outside the default boostrap look, since otherwise wi'll get a mess a and not a UI :)

To brake down the image above:

- remove the box with the drag and drop image that you added. we keep the drag and drop functionality, but we don't make it clear that we support it, if someone drags a file, cool. but the main way to add a file is from the file picker, that we originally had
- remove the right column
- under from and to, put the file picker to get the full lenght
- beneeth the file picker, you display the selected file, and next to this, display the stats.

Make sure that on mobile, all the elements that are next to each other, will be displayed one under the other, and that is that :)

**Comment by rheckart** [comment]
- Removed the drag/drop image & area.
- Drag/drop now works on the entire document area.
- Removed the right column. 
- File picker is now full-length.
- Selected filename now shows underneath the file picker. 
- Mobile enhancements made to show email inputs vertically on small devices.
- Vertical spacing equalized in bottom area.
